<?php

namespace WebExcess\Comments\Domain\Model;

/*
 * This file is part of the WebExcess.Comments package.
 *
 * (c) Contributors of the Neos Project - www.neos.io
 *
 * This package is Open Source Software. For the full copyright and license
 * information, please view the LICENSE file which was distributed with this
 * source code.
 */

use Neos\ContentRepository\Domain\Model\NodeInterface;
use Neos\Flow\Annotations as Flow;

class CommentFeUserOnly extends CommentAbstract implements CommentInterface
{

    /**
     * @var string
     */
    protected $firstname;

    /**
     * @var string
     */
    protected $lastname;

    /**
     * @var string
     */
    protected $email;

    public function loadNodeData(NodeInterface $node = null)
    {
        parent::loadNodeData($node); // TODO: Change the autogenerated stub
    }

    public function loadAccountDataIfAuthenticated()
    {
        return parent::loadAccountDataIfAuthenticated(); // TODO: Change the autogenerated stub
    }

}
